config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  root 'home#index'
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
      devise_parameter_sanitizer.permit(:account_update, keys: %i[name role first_login])
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @quote_list =  [
      {
          quote: "We can only see a little bit of the future, but enough to know there is much to do",
          author: "Alan Mathison Turing"
      },
      {
          quote: "Setting goals is the first step in turning the invisible into the visible",
          author: "Tony Robbins"
      },
      {
          quote: "Goals are like magnets. They attract the things that you need and help determine what you want to become",
          author: "Zig Ziglar"
      },
      {
          quote: "Dreams can become a reality when we possess the courage to pursue them",
          author: "Walt Disney"
      },
      {
          quote: "Success is the sum of small efforts repeated day in and day out",
          author: "Robert Collier"
      },
      {
          quote: "Set a goal that makes you want to jump out of bed in the morning",
          author: "Unknown"
      },
      {
          quote: "The only limit to your dreams is your imagination and determination",
          author: "Unknown"
      },
      {
          quote: "If you can dream it, you can achieve it",
          author: "Zig Ziglar"
      },
      {
          quote: "A goal without a plan is just a wish",
          author: "Antoine de Saint-Exupéry"
      },
      {
          quote: "Success is the sum of small efforts repeated day in and day out",
          author: "Leo Tolstoy"
      },
      {
          quote: "If you want something you've never had, you must be willing to do something you've never done",
          author: "Unknown"
      },
      {
          quote: "Great achievements are possible when we give importance to small beginnings",
          author: "Lao Tzu"
      },
      {
          quote: "Don't wait for opportunity. Create it",
          author: "Unknown"
      },
      {
          quote: "The future belongs to those who believe in the beauty of their dreams",
          author: "Eleanor Roosevelt"
      },
      {
          quote: "The only way to achieve the impossible is to believe it is possible",
          author: "Charles Kingsleigh"
      },
      {
          quote: "Don't let the fear of falling stop you from flying",
          author: "Unknown"
      },
      {
          quote: "If you're not willing to risk, you cannot grow",
          author: "Unknown"
      },
      {
          quote: "Success is the sum of small efforts repeated day in and day out",
          author: "Robert Collier"
      },
      {
          quote: "Dreams are postponed only to be realized",
          author: "Unknown"
      },
      {
          quote: "The way to get started is to stop talking and start doing",
          author: "Walt Disney"
      }
  ]
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
    <%= render template: "layouts/_base-hero" %>

app/views/layouts/_base-hero.html.erb
<div class="banner">
  <%= image_tag "banner.png", alt: "Banner", class: "banner__image" %>
  <div class="banner__overlay">
    <div class="banner__overlay--text">
      <h2 class="banner__overlay--text-quote" id="quote">
        <%= @quote_list.first[:quote].to_json.html_safe %>
      </h2>
      <div class="banner__divider"></div>
      <h4 class="banner__overlay--text-author">
        <%= @quote_list.first[:author].to_json.html_safe %>
      </h4>
    </div>
  </div>
</div>

<script>
  let currentIndex = 0;
  const quotes = <%= @quote_list.to_json.html_safe %>;

  document.addEventListener("DOMContentLoaded", function() {
    setInterval(updateQuote, 5000);

    function updateQuote() {
      const quoteElement = document.getElementById("quote");
      const authorElement = document.querySelector(".banner__overlay--text-author");

      currentIndex = (currentIndex + 1) % quotes.length;
      const currentQuote = quotes[currentIndex];

      quoteElement.innerText = currentQuote.quote;
      authorElement.innerText = currentQuote.author;
    }
  });
</script>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
    <ul class="navbar-nav">
        <li class="nav-item">
            <%= link_to 'Home', home_index_path, class: 'nav-link' %>
        </li>
        <% if current_user %>
            <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to "Log In", new_user_session_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PgV2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Zilla+Slab:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render template: "layouts/_navbar" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>

  </body>
</html>